### ISSUE TITLE
nsqlookupd DNS wrongly inferred

### ISSUE THREAD

**Issue by philicious** [BeeInventor/charts#16]
I noticed a bug here https://github.com/BeeInventor/charts/blob/main/beeinventor/nsq/templates/nsqd-statefulset.yaml#L43-L46 and here https://github.com/BeeInventor/charts/blob/main/beeinventor/nsq/templates/nsqd-statefulset.yaml#L43-L46

the nsqlookupd DNS results to `nsq-nsqlookupd-0.nsq-nsqlookupd:4160` in my case (with helm release name `nsq`).
The DNS is wrong. 

Instead of repeating the lookup address for each replica, you should address the service, which balances over the replicas anyways. 

I was able to workaround by doing
```
      - nsqd:
          extraArgs:
            - "--lookupd-tcp-address=nsq-nsqlookupd:4160"
..

      - nsqadmin:
          extraArgs:
            - "--lookupd-http-address=nsq-nsqlookupd:4161" # chart has a bug and inserts wrong dns name
..
```

however this only adds the correct address but I cannot override the original args, which leaves errors in logs as is still tries to also call the wrong one
