### ISSUE TITLE
Invalid NSQD service port protocol

### ISSUE THREAD

**Issue by LordNoteworthy** [BeeInventor/charts#4]
Hi @benjamin658 

I believe there is a small issue in the service definition of NSQD.

There is no `HTTP` protocol port. Only `SCTP`, `TCP`, `UDP` are supported in a kubernetes svc.

```yaml
spec:
  type: {{ .Values.nsqd.service.type }}
  ports:
  - name: http
    port: 4151
    targetPort: http
    protocol: HTTP <== to change to TCP
  - name: tcp
    port: 4150
    protocol: TCP
    targetPort: tcp
```

Cheers.
