### ISSUE TITLE
nsq: make nsqadmin wait for lookupd

### ISSUE THREAD

**Issue by ayoubfaouzi** [BeeInventor/charts#8]
Hello @benjamin658 

This is not a bug, but probably an enhancement we can do to nsqadmin.

What basically happens when you install the chart, nsqadmin is the first candidate that quickly get fetched and when the container run, it output the following error:

```shell
[nsqadmin] 2021/08/18 09:32:32.771223 FATAL: failed to instantiate nsqadmin -
failed to resolve --lookupd-http-address (jupiter-nsqlookupd-0.jupiter-nsqlookupd:4161) -
lookup jupiter-nsqlookupd-0.jupiter-nsqlookupd on 10.96.0.10:53: no such host
```

Then it get restarted for few times until nsqlookupd is ready, then it starts. It looks a bit ugly to see that the container has crashed few times.

This is normal because nsqadmin does not wait for lookupd to start. I have this problem anytime I have a container which depends on another one. The way I get arround this is by adding an side car container that wait for the dependency to show up. Something like this:

```yaml
initContainers:
  - name: wait-for-db
    image: groundnuty/k8s-wait-for:v1.3
    imagePullPolicy: Always
    args:
      - "pod"
        - "-lapp=mysql"
  ```

Not sure if this is the best way to do it :)

Cheers.
